import logging
from pathlib import Path

DEFAULT_LOGGING_DEBUG_LEVEL = logging.DEBUG

DELETE_TEMP_FOLDER_ON_STARTUP = True
TEMP_FOLDER_NAME = "M0WUT_tools"

PROJECT_JSON_PATH = Path("project.json")

PROJECT_NUMBER_TRACKER_REPO_NAME = "project-tracker"


GITHUB_PAGES_DEPLOYMENT_WORKFLOW_NAME = "main.yml"

TEMPLATE_PROJECT_REPO_OWNER = "M0WUT"
TEMPLATE_PROJECT_REPO_NAME = "p0002-001_template-board"

RELEASER_PROJECT_REPO_OWNER = "M0WUT"
RELEASER_PROJECT_REPO_NAME = "kicad_releaser"
