PROJECT_NUMBER_TRACKER_REPO_NAME = "project-tracker"
TEMP_FOLDER_NAME = "M0WUT_tools"

GITHUB_PAGES_DEPLOYMENT_WORKFLOW_NAME = "main.yml"

TEMPLATE_PROJECT_REPO_OWNER = "M0WUT"
TEMPLATE_PROJECT_REPO_NAME = "p0002_kicad-template-project"

RELEASER_PROJECT_REPO_OWNER = "M0WUT"
RELEASER_PROJECT_REPO_NAME = "kicad_releaser"
